**Problem 3**
$$
A_1 =
\begin{bmatrix}
\cos\theta_1 & 0 & \sin\theta_1 & 0 \\
\sin\theta_1 & 0 & -\cos\theta_1 & 0 \\
0 & 1 & 0 & 13 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
A_2 =
\begin{bmatrix}
\cos\theta_2 & -\sin\theta_2 & 0 & 8\cos\theta_2 \\
\sin\theta_2 & \cos\theta_2 & 0 & 8\sin\theta_2 \\
0 & 0 & 1 & d_2 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
A_3 =
\begin{bmatrix}
\cos\!\left(\frac{\pi}{2}+\theta_3\right) & 0 & \sin\!\left(\frac{\pi}{2}+\theta_3\right) & 0 \\
\sin\!\left(\frac{\pi}{2}+\theta_3\right) & 0 & -\cos\!\left(\frac{\pi}{2}+\theta_3\right) & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
A_4 =
\begin{bmatrix}
\cos\theta_4 & 0 & -\sin\theta_4 & 0 \\
\sin\theta_4 & 0 & \cos\theta_4 & 0 \\
0 & -1 & 0 & 8 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
A_5 =
\begin{bmatrix}
\cos\!\left(\frac{\pi}{2}-\theta_5\right) & 0 & \sin\!\left(\frac{\pi}{2}-\theta_5\right) & 0 \\
-\sin\!\left(\frac{\pi}{2}-\theta_5\right) & 0 & \cos\!\left(\frac{\pi}{2}-\theta_5\right) & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
A_6 =
\begin{bmatrix}
\cos\theta_6 & -\sin\theta_6 & 0 & 0 \\
\sin\theta_6 & \cos\theta_6 & 0 & 0 \\
0 & 0 & 1 & d_6 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$
T_0^6
= A_1 A_2 A_3 A_4 A_5 A_6
$$

$$
T_0^6
=
\begin{bmatrix}
\cos\theta_1 & 0 & \sin\theta_1 & 0 \\
\sin\theta_1 & 0 & -\cos\theta_1 & 0 \\
0 & 1 & 0 & 13 \\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\theta_2 & -\sin\theta_2 & 0 & 8\cos\theta_2 \\
\sin\theta_2 & \cos\theta_2 & 0 & 8\sin\theta_2 \\
0 & 0 & 1 & d_2 \\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\!\left(\frac{\pi}{2}+\theta_3\right) & 0 & \sin\!\left(\frac{\pi}{2}+\theta_3\right) & 0 \\
\sin\!\left(\frac{\pi}{2}+\theta_3\right) & 0 & -\cos\!\left(\frac{\pi}{2}+\theta_3\right) & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}

\quad\quad\cdot
\begin{bmatrix}
\cos\theta_4 & 0 & -\sin\theta_4 & 0 \\
\sin\theta_4 & 0 & \cos\theta_4 & 0 \\
0 & -1 & 0 & 8 \\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\!\left(\frac{\pi}{2}-\theta_5\right) & 0 & \sin\!\left(\frac{\pi}{2}-\theta_5\right) & 0 \\
-\sin\!\left(\frac{\pi}{2}-\theta_5\right) & 0 & \cos\!\left(\frac{\pi}{2}-\theta_5\right) & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\theta_6 & -\sin\theta_6 & 0 & 0 \\
\sin\theta_6 & \cos\theta_6 & 0 & 0 \\
0 & 0 & 1 & d_6 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

In [ ]:
import sympy as sp

theta1, theta2, theta3, theta4, theta5, theta6 = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
d2, d6 = sp.symbols('d2 d6')

c1, s1 = sp.cos(theta1), sp.sin(theta1)
c2, s2 = sp.cos(theta2), sp.sin(theta2)
c3p = sp.cos(sp.pi/2 + theta3)
s3p = sp.sin(sp.pi/2 + theta3)
c4, s4 = sp.cos(theta4), sp.sin(theta4)
c5m = sp.cos(sp.pi/2 - theta5)
s5m = sp.sin(sp.pi/2 - theta5)
c6, s6 = sp.cos(theta6), sp.sin(theta6)

# A1
A1 = sp.Matrix([
    [c1, 0,  s1, 0],
    [s1, 0, -c1, 0],
    [0,  1,  0,  13],
    [0,  0,  0,  1]
])

# A2
A2 = sp.Matrix([
    [c2, -s2, 0, 8*c2],
    [s2,  c2, 0, 8*s2],
    [0,   0,  1, d2],
    [0,   0,  0, 1]
])

# A3 (with pi/2 + theta3 kept as-is)
A3 = sp.Matrix([
    [c3p, 0,  s3p, 0],
    [s3p, 0, -c3p, 0],
    [0,   1,  0,   0],
    [0,   0,  0,   1]
])

# A4 (using 8 as in your matrix; swap 8 -> d4 if needed)
A4 = sp.Matrix([
    [c4, 0, -s4, 0],
    [s4, 0,  c4, 0],
    [0, -1,  0,  8],
    [0,  0,  0,  1]
])

# A5 (with pi/2 - theta5 kept as-is)
A5 = sp.Matrix([
    [c5m,  0,  s5m, 0],
    [-s5m, 0,  c5m, 0],
    [0,   -1,  0,   0],
    [0,    0,  0,   1]
])

# A6
A6 = sp.Matrix([
    [c6, -s6, 0, 0],
    [s6,  c6, 0, 0],
    [0,    0, 1, d6],
    [0,    0, 0, 1]
])

# Full forward kinematics
T06 = sp.simplify(A1 * A2 * A3 * A4 * A5 * A6)

# Pretty print
sp.pprint(T06)

# LaTeX output
print("\nLaTeX form:\n")
print(sp.latex(T06))

⎡((sin(θ₁)⋅sin(θ₄) - sin(θ₂ + θ₃)⋅cos(θ₁)⋅cos(θ₄))⋅sin(θ₅) + cos(θ₁)⋅cos(θ₅)⋅c ↪
⎢                                                                              ↪
⎢-((sin(θ₁)⋅sin(θ₂ + θ₃)⋅cos(θ₄) + sin(θ₄)⋅cos(θ₁))⋅sin(θ₅) - sin(θ₁)⋅cos(θ₅)⋅ ↪
⎢                                                                              ↪
⎢                                (sin(θ₅)⋅cos(θ₄)⋅cos(θ₂ + θ₃) + sin(θ₂ + θ₃)⋅ ↪
⎢                                                                              ↪
⎣                                                                              ↪

↪ os(θ₂ + θ₃))⋅cos(θ₆) - (sin(θ₁)⋅cos(θ₄) + sin(θ₄)⋅sin(θ₂ + θ₃)⋅cos(θ₁))⋅sin( ↪
↪                                                                              ↪
↪ cos(θ₂ + θ₃))⋅cos(θ₆) - (sin(θ₁)⋅sin(θ₄)⋅sin(θ₂ + θ₃) - cos(θ₁)⋅cos(θ₄))⋅sin ↪
↪                                                                              ↪
↪ cos(θ₅))⋅cos(θ₆) + sin(θ₄)⋅sin(θ₆)⋅cos(θ₂ + θ₃)                              ↪
↪                          

In [4]:
import pandas as pd
import numpy as np
import math

# Define the DH table directly as a DataFrame
dh = pd.DataFrame([
    # a, alpha, d, theta, joint_type
    [0,     0,   'd1',   'theta1', 'R'],   # Joint 1: revolute
    [0,   -90,   'd2',   0,        'P'],   # Joint 2: prismatic
    [0,     0,   'd3',   0,        'P'],   # Joint 3: prismatic
], columns=['a', 'alpha', 'd', 'theta', 'type'])

print(dh)

   a  alpha   d   theta type
0  0      0  d1  theta1    R
1  0    -90  d2       0    P
2  0      0  d3       0    P


In [6]:
def dh_to_A(a, alpha, d, theta):
    alpha = math.radians(alpha)
    theta = math.radians(theta)
    ca, sa = math.cos(alpha), math.sin(alpha)
    ct, st = math.cos(theta), math.sin(theta)

    return np.array([
        [ct, -st*ca,  st*sa, a*ct],
        [st,  ct*ca, -ct*sa, a*st],
        [0,      sa,     ca,   d ],
        [0,       0,      0,   1 ]
    ])

def forward_kinematics(dh, joint_values):
    T = np.eye(4)

    for _, row in dh.iterrows():
        a = float(row['a'])
        alpha = float(row['alpha'])

        # Resolve d and theta depending on joint type
        if row['type'] == 'R':
            theta = float(joint_values[row['theta']])
            d = float(joint_values[row['d']]) if isinstance(row['d'], str) else float(row['d'])
        else:  # prismatic
            d = float(joint_values[row['d']])
            theta = float(joint_values[row['theta']]) if isinstance(row['theta'], str) else float(row['theta'])

        A = dh_to_A(a, alpha, d, theta)
        T = T @ A

    return T

In [7]:
joint_values = {
    'theta1': 45,   # degrees
    'd1': 0.1,      # meters
    'd2': 0.3,
    'd3': 0.5
}

T03 = forward_kinematics(dh, joint_values)
print(T03)

[[ 7.07106781e-01 -4.32978028e-17 -7.07106781e-01 -3.53553391e-01]
 [ 7.07106781e-01  4.32978028e-17  7.07106781e-01  3.53553391e-01]
 [ 0.00000000e+00 -1.00000000e+00  6.12323400e-17  4.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
